### ISSUE TITLE
Invalid or unexpected token

### ISSUE THREAD

**Issue by kouguopeng** [fuxingZhang/egg-mysql#3]
_@node-mysql_mysql@0.8.0@@node-mysql/mysql/lib/pool.js:8
  #pool;
  ^
SyntaxError: Invalid or unexpected token
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/kouguopeng/Desktop/2020622/ptgnbackstage/node_modules/_@node-mysql_mysql@0.8.0@@node-mysql/mysql/index.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

**Comment by fuxingZhang** [comment]
example
